### ISSUE TITLE
Get private messages since specified timestamp

### ISSUE THREAD

**Issue by TyMarc** [TyMarc/blindr-backend#2]

**Comment by TyMarc** [comment]
Private messages will be saved in local db to have a quicker response from the server and lessen the network bandwidth

**Comment by leameow** [comment]
Reopening since we should try to filter from the query itself in the future. Also missing [unit tests](https://github.com/TyMarc/blindr-backend/blob/master/tests/models/test_event.py)!

**Comment by TyMarc** [comment]
query key condition not supported error with
sent_at__gt=since

**Comment by leameow** [comment]
Relevant exception: https://rollbar.com/blindr-backend/blindr-backend/items/6/
